### PR TITLE
Migrate to minitest

### LINKED ISSUE #316: Switch to Minitest
Rspec is not always compatible with the latest changes in Rails. 
Switching to minitest should be trivial and a good exercise for someone who want to get his/her hand on Opensource contributions.

Migrating to minitest should not be in one block, we can have both minitest and rspec running different tests until we migrate all.

We can use this thread to synchronize the effort and avoid the double work.

### PR DESCRIPTION
**Pull request by seuros**
reference #316

### CODE REVIEW

**Comment by alagram** [comment]
@seuros I'd like to take up this task and continue the minitest migration.

**Comment by seuros** [comment]
@alagram Cool. Looking forward your contribution. Let me know if you need assistance.

I will merge this PR so you can open a PR against the primary branch.

**Comment by alagram** [comment]
> @alagram Cool. Looking forward your contribution. Let me know if you need assistance.
> 
> I will merge this PR so you can open a PR against the primary branch.

Will do, thank you!

**Comment by seuros** [comment]
Open smaller PRs, it will be better for review.

**Pull request merged**
