### PR TITLE
Test on Rails 5.2 & fix mysql for older Rails

### PR DESCRIPTION
**Pull request by swrobel**

### CODE REVIEW

**Comment by mceachen** [comment]
Nice!

Boy howdy is that a serious test matrix now--Travis builds look like they will go from 40 minutes (!) to  over an hour (!!). I was hoping we could drop some of those ruby versions, but as of this moment, they're all [currently supported](https://www.ruby-lang.org/en/downloads/). 2.2 should EOL soon.

Perhaps we should remove the tests whose results we always discard, like 2.6 and activerecord_edge?

**Comment by swrobel** [comment]
FYI I have an issue open w/ Travis about the 2.6 build failing https://github.com/travis-ci/travis-ci/issues/9383#issuecomment-375994207

**Comment by mceachen** [comment]
Yeah, that build took 80 minutes, so it doubled. Do you think we should include all the ruby versions? I don't remember ever seeing a difference in how 2.x rubies performed in tests (whereas there certainly was between 1.x and 2.x, of course).

**Comment by swrobel** [comment]
Good point. I think it can be cut down to oldest supported version. Activrecord versions are more important.

**Pull request merged**
