### PR TITLE
fixed generator specs and added migration version

### PR DESCRIPTION
**Pull request by emptyflask**
Rails 5.x expects migrations to subclass `ActiveRecord::Migration[5.x]`

### CODE REVIEW

**Comment by seuros** [comment]
Thank you @emptyflask for this fix.
It will break in rails 4.2 :(

let me think about a solution

**Comment by emptyflask** [comment]
Will it? Under Rails 4, the version should just be nil. Or will it fail for some other reason?

**Comment by seuros** [comment]
You sure ? I think it will be ActiveRecord::Migration4

**Comment by seuros** [comment]
Nevermind. It works 👍

**Pull request merged**
