### PR TITLE
Performance tweaks

### PR DESCRIPTION
**Pull request by magnusfiorepalm**
We noticed that certain queries using sub selects are fairly slow on a bigger recordset. Our hierarchy table contains 80+ million records causing these queries to take a long time.

The added additional queries avoid the performance issue by minimizing the record sets in the sub selects before the join with the outer table.

### CODE REVIEW

**Comment by mceachen** [comment]
Thanks for the PR! Sorry for the latency.

I fixed the merge conflicts in my branch. If you want to check out my branch and verify my change to the `hash_tree` query is still performant, that'd be great—it's not quite the same, but it should still work.

**Comment by magnusfiorepalm** [comment]
Fantastic! I'll take a look. 

Did you also pull in the changes to hierachy_maintenance.rb? https://github.com/mceachen/closure_tree/pull/178/files#diff-693c6ab46fe400dd004a79a24ab8d56bR97

**Comment by mceachen** [comment]
If you want to check out where this PR stands, check out my branch https://github.com/mceachen/closure_tree/tree/magnusfiorepalm-master and take it from there. One test is failing, and, super-irritatingly, only on sqlite: https://travis-ci.org/mceachen/closure_tree/jobs/88727157

**Comment by mceachen** [comment]
(also make sure you try out version 6.0.0 that I just released, there's a DELETE clause that should dramatically help mutation performance for your large trees!)

**Pull request closed without merging**
