### PR TITLE
Migrate from Travis to Github Actions

### PR DESCRIPTION
**Pull request by n-rodriguez**
Fix https://github.com/ClosureTree/closure_tree/issues/371

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Yeah!  : https://github.com/n-rodriguez/closure_tree/actions/runs/473263289 :rocket:

**Comment by n-rodriguez** [comment]
ping @seuros

**Comment by n-rodriguez** [comment]
Latest build : https://github.com/n-rodriguez/closure_tree/actions/runs/473327985

**Comment by seuros** [comment]
Excellent work Nicolas

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
