### PR TITLE
Added ability to touch the parent 

### PR DESCRIPTION
**Pull request by seuros**
Just add :touch => true to the options of acts_as_tree.

### CODE REVIEW

**Comment by mgwidmann** [comment]
Caching is broken without this feature... sad, have to implement your own touch functionality. :-1:

**Comment by seuros** [comment]
I reimplemented it in another commit. just add `touch: true` to the ct options

**Comment by mgwidmann** [comment]
Well then this feature is broken. Using version `5.2.0` the following code does not work as expected:
(Below I've changed the model and ids, but I did run this code in my app)
```
child = MyTree.find(123)
parent = Mytree.find(456)
parent.children     # #<ActiveRecord::Associations::CollectionProxy []>
child.parent          # nil
child.update(parent_id: parent.id)
child.updated_at       # Mon, 15 Jun 2015 11:13:38 EDT -04:00
parent.updated_at    # Mon, 15 Jun 2015 10:52:53 EDT -04:00
```

**Comment by mgwidmann** [comment]
As the documentation in the README says:  

```
:touch delegates to the belongs_to annotation for the parent, so touching cascades to all children (the performance of this for deep trees isn't currently optimal).
```

It does not touch parents (`touching cascades to all children`).

**Comment by mgwidmann** [comment]
My workaround:

```
before_save do
    if parent_id_changed?
      self.class.where(id: [parent_id, parent_id_was].compact).update_all(updated_at: Time.now)
    end
  end
```

Successfully busts the cache when `child.update(parent_id: new_parent.id)` is called, busting both old parent and new parent. Does not do recursive busting.

**Pull request closed without merging**
